[package]
name = "flow_hematite"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "flow_hematite"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
hematite-nbt = "0.5.2"